branches:
  only:
  - master
  - "/^v.*$/"
language: python
sudo: false
python:
- 3.8
- 3.9
install:
- pip install --upgrade pip
- pip install --upgrade -r requirements.txt
- pip install -e .
script:
- pytest -v
